 Create and Edit Aura Components/force-app/main/default/objects/Dispenser_account__c/Dispenser_account__c.object-meta.xml
<CustomObject>
    <label>Dispenser account</label>
    <nameField>
        <displayFormat>DAcc-{0000}</displayFormat>
        <label>Dispenser  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dispenser accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

 Create and Edit Aura Components/force-app/main/default/objects/Dispenser_account__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Balance</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

 Create and Edit Aura Components/force-app/main/default/objects/Dispenser_account__c/fields/Bank_owner__c.field-meta.xml
<CustomField>
    <fullName>Bank_owner__c</fullName>
    <label>Bank owner</label>
    <referenceTo>Dispenser_bank__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Dispenser_accounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

 Create and Edit Aura Components/force-app/main/default/objects/Dispenser_account__c/fields/Card_number__c.field-meta.xml
<CustomField>
    <fullName>Card_number__c</fullName>
    <label>Card number</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

 Create and Edit Aura Components/force-app/main/default/objects/Dispenser_account__c/fields/Currency_type__c.field-meta.xml
<CustomField>
    <fullName>Currency_type__c</fullName>
    <label>Currency type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RUB</fullName>
                <default>true</default>
                <label>RUB</label>
            </value>
            <value>
                <fullName>BYN</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

 Create and Edit Aura Components/force-app/main/default/objects/Dispenser_account__c/fields/Is_credit_card__c.field-meta.xml
<CustomField>
    <fullName>Is_credit_card__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is credit card</label>
    <type>Checkbox</type>
</CustomField>

 Create and Edit Aura Components/force-app/main/default/objects/Dispenser_account__c/fields/maximum_loan_amount__c.field-meta.xml
<CustomField>
    <fullName>maximum_loan_amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>maximum loan amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

 Create and Edit Aura Components/force-app/main/default/objects/Dispenser_account__c/fields/PIN__c.field-meta.xml
<CustomField>
    <fullName>PIN__c</fullName>
    <label>PIN</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

 Create and Edit Aura Components/force-app/main/default/objects/Dispenser_account__c/fields/Withdraw__c.field-meta.xml
<CustomField>
    <fullName>Withdraw__c</fullName>
    <label>Withdrawal currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>RUB</fullName>
                <default>true</default>
                <label>RUB</label>
            </value>
            <value>
                <fullName>BYN</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

 Create and Edit Aura Components/force-app/main/default/classes/dispenserController.cls
public with sharing class dispenserController
{

	@AuraEnabled
	public static Dispenser_account__c getAccount(String cardNumber, String PIN)
	{
		List <Dispenser_account__c>			accounts;

		System.debug('cardNumber ' + cardNumber + 'PIN' + PIN);
		accounts =
		[
			SELECT Id, Name, Is_credit_card__c, maximum_loan_amount__c,
				Bank_owner__c, Balance__c, Currency_type__c, Withdraw__c
			FROM Dispenser_account__c
			WHERE
				(Dispenser_account__c.Card_number__c = :cardNumber) AND
				(Dispenser_account__c.PIN__c = :PIN)
		];
		System.debug('accounts[0]' + accounts[0]);
		return (accounts[0]);
	}

	@AuraEnabled
	public static Dispenser_account__c saveAccount(Dispenser_account__c account)
	{
		/*
		** Perform isUpdateable() checking first, then
		*/
		upsert account;
		return (account);
	}

}

// dispenserController.getAccount('1000000001', '1001');