IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/Catalog_Template__c.object-meta.xml
<CustomObject>
    <label>Catalog Template</label>
    <nameField>
        <label>Catalog Template  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalog Template</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/fields/Category_Text_Color__c.field-meta.xml
<CustomField>
    <fullName>Category_Text_Color__c</fullName>
    <defaultValue>&quot;#EEEEEE&quot;</defaultValue>
    <label>Category Text Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/fields/Header_Left_Text_Color__c.field-meta.xml
<CustomField>
    <fullName>Header_Left_Text_Color__c</fullName>
    <defaultValue>&quot;#EEEEEE&quot;</defaultValue>
    <label>Header Left Text Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/fields/Header_Right_Text_Color__c.field-meta.xml
<CustomField>
    <fullName>Header_Right_Text_Color__c</fullName>
    <defaultValue>&quot;#FFFFFF&quot;</defaultValue>
    <label>Header Right Text Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/fields/Subtitle_Text__c.field-meta.xml
<CustomField>
    <fullName>Subtitle_Text__c</fullName>
    <defaultValue>&quot;WELCOME TO OUR CATALOG!&quot;</defaultValue>
    <label>Subtitle Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/fields/Subtitle_Text_Color__c.field-meta.xml
<CustomField>
    <fullName>Subtitle_Text_Color__c</fullName>
    <defaultValue>&quot;#FFFFFF&quot;</defaultValue>
    <label>Subtitle Text Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/fields/Subtitle_Text_Size__c.field-meta.xml
<CustomField>
    <fullName>Subtitle_Text_Size__c</fullName>
    <label>Subtitle Text Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>18px</fullName>
            </value>
            <value>
                <fullName>24px</fullName>
            </value>
            <value>
                <fullName>36px</fullName>
                <default>true</default>
                <label>36px</label>
            </value>
            <value>
                <fullName>48px</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/fields/Title_Text__c.field-meta.xml
<CustomField>
    <fullName>Title_Text__c</fullName>
    <defaultValue>&quot;FORCE.COM LABS&quot;</defaultValue>
    <label>Title Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/fields/Title_Text_Color__c.field-meta.xml
<CustomField>
    <fullName>Title_Text_Color__c</fullName>
    <defaultValue>&quot;#FFF6C8&quot;</defaultValue>
    <label>Title Text Color</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Template__c/fields/Title_Text_Size__c.field-meta.xml
<CustomField>
    <fullName>Title_Text_Size__c</fullName>
    <label>Title Text Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>40px</fullName>
            </value>
            <value>
                <fullName>48px</fullName>
            </value>
            <value>
                <fullName>56px</fullName>
            </value>
            <value>
                <fullName>64px</fullName>
                <default>true</default>
                <label>64px</label>
            </value>
            <value>
                <fullName>72px</fullName>
            </value>
            <value>
                <fullName>80px</fullName>
            </value>
            <value>
                <fullName>84px</fullName>
            </value>
            <value>
                <fullName>88px</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IntershipFirstProject/force-app/main/default/classes/CatalogConfiguration.cls
public with sharing class CatalogConfiguration {

    Transient Document CatalogBackgroundImage {get;set;}
    Public Catalog_Template__c myCatalogTemplate {get;set;}
    Public Catalog_Template__c myExistingCatalogTemplate {get;set;}
    Public transient Blob b {get;set;}
    Public Integer bSize {get;set;}

    public CatalogConfiguration() {
        initialize();
    }
    
    public PageReference initialize() {
        if(!Catalog_Template__c.sObjectType.getDescribe().isCreateable()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Insufficient access'));
            return null;
        }
        //Check for Template Record, if NULL Create new Catalog Template with values from brander
        Integer TemplateCheck = [SELECT count() FROM Catalog_Template__c WHERE Name = 'Catalog Template 1'];
        bSize = 0;
        if(TemplateCheck == 0) {
            // No Template exists, so make one
            myCatalogTemplate = new Catalog_Template__c();
            myCatalogTemplate.Name = 'Catalog Template 1';
            // We made a new Template
        } else {
            // Template exists, so grab it to edit
            myCatalogTemplate = [SELECT Id, Title_Text__c, Title_Text_Color__c, Title_Text_Size__c, Subtitle_Text__c, Subtitle_Text_Color__c, Subtitle_Text_Size__c, Category_Text_Color__c, Header_Left_Text_Color__c, Header_Right_Text_Color__c FROM Catalog_Template__c WHERE Name = 'Catalog Template 1' LIMIT 1];
            // We have the existing Template
        }
        return null;
    }
    
    public PageReference saveTemplate() {
        if(!Catalog_Template__c.sObjectType.getDescribe().isCreateable()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Insufficient access'));
            return null;
        }
        upsert myCatalogTemplate;
        return null;
    }

    public PageReference saveFile() {
        if(!Document.sObjectType.getDescribe().isAccessible()) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.FATAL,'Insufficient access'));
            return null;
        }
        //update the Document named Catalog_BG
        if (bSize > 0) {
            System.debug('DOCUMENT: The blob had size > 0 - so we are updating CatalogBackgroundImage.');
            CatalogBackgroundImage = [SELECT Body FROM Document WHERE name = 'Catalog_BG' LIMIT 1];
            // We have the background document
            CatalogBackgroundImage.Body = b;
            update CatalogBackgroundImage;
        } else { 
            // DOCUMENT: No file was uploaded - so do not update CatalogBackgroundImage
        }
        return null;
    }
}