IntershipFirstProject/force-app/main/default/objects/Catalog_Line_Item__c/Catalog_Line_Item__c.object-meta.xml
<CustomObject>
    <description>A line item in a Catalog Order for use with the Catalog mobile app.</description>
    <label>Catalog Line Item</label>
    <nameField>
        <displayFormat>CLI-{00000}</displayFormat>
        <label>Catalog Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Catalog Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

IntershipFirstProject/force-app/main/default/objects/Catalog_Line_Item__c/fields/Catalog_Order__c.field-meta.xml
<CustomField>
    <fullName>Catalog_Order__c</fullName>
    <label>Order</label>
    <referenceTo>Catalog_Order__c</referenceTo>
    <relationshipLabel>Catalog Line Items</relationshipLabel>
    <relationshipName>Catalog_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Catalog Line Items</relationshipLabel>
    <relationshipName>Catalog_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Line_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Line_Item__c/fields/VF_Image__c.field-meta.xml
<CustomField>
    <fullName>VF_Image__c</fullName>
    <formula>Product__r.VF_Image__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VF Image</label>
    <type>Text</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Order__c/Catalog_Order__c.object-meta.xml
<CustomObject>
    <description>A Catalog Order for use with the Catalog mobile app.</description>
    <label>Catalog Order</label>
    <nameField>
        <displayFormat>CO-{00000}</displayFormat>
        <label>Catalog Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Catalog Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

IntershipFirstProject/force-app/main/default/objects/Catalog_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Catalog Orders</relationshipLabel>
    <relationshipName>Catalog_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

IntershipFirstProject/force-app/main/default/objects/Catalog_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cart</fullName>
                <default>true</default>
                <label>Cart</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

IntershipFirstProject/force-app/main/default/classes/ProductCatalogController.cls
public with sharing class ProductCatalogController {

    @AuraEnabled
	public static List<Product2> getProducts() {
	    // Check if we can view fields on Product
        Map<String,Schema.SObjectField> fieldDescribeTokens =
                Schema.SObjectType.Product2.fields.getMap();
        String[] fieldsToCheck = new String[] {'Id','Name','Family', 'VF_Image__c',
                'Default_Price__c','Inventory__c','Description'};
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException(); return null;
            }
        }
	    // LETS GO!
        return [SELECT Id, Name, Family, Default_Price__c,
                Inventory__c,Description,VF_Image__c
            FROM Product2
            WHERE Family != null
            ORDER BY Family ASC, Name ASC NULLS FIRST];
	}
    
    @AuraEnabled
    public static string createCatalogOrder(String accountId, List<Catalog_Line_Item__c> items) {
        // Check if we can view fields on Orders
        Map<String,Schema.SObjectField> fieldDescribeTokens =
                Schema.SObjectType.Catalog_Order__c.fields.getMap();
        String[] fieldsToCheck = new String[]{'Id','Name'};
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException(); return null;
            }
        }
        // Check if we can create fields on Orders
        fieldDescribeTokens =
                Schema.SObjectType.Catalog_Order__c.fields.getMap();
        fieldsToCheck = new String[]{'Account__c','Status__c'};
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isCreateable()) {
                throw new System.NoAccessException(); return null;
            }
        }
        // Check if we can create fields on LineItems
        fieldDescribeTokens =
                Schema.SObjectType.Catalog_Line_Item__c.fields.getMap();
        fieldsToCheck = new String[]{'Product__c','Quantity__c','Catalog_Order__c'};
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isCreateable()) {
                throw new System.NoAccessException(); return null;
            }
        }
        // LETS GO!
        Catalog_Order__c newOrder = new Catalog_Order__c();
        newOrder.Account__c = accountId;
        newOrder.Status__c = 'Submitted';

        insert newOrder;
        List<Catalog_Line_Item__c> lineItems =
                new List<Catalog_Line_Item__c>();
        for (Catalog_Line_Item__c lineItem : items) {
            lineItem.Catalog_Order__c = newOrder.Id;
            lineItems.add(lineItem);
        }
        insert lineItems;
        return [SELECT Name FROM Catalog_Order__c WHERE Id =: newOrder.Id].Name;
    }
    
    @AuraEnabled
    public static List<Account> getAccounts() {
        // Check if we can view fields on Account
        Map<String,Schema.SObjectField> fieldDescribeTokens =
                Schema.SObjectType.Account.fields.getMap();
        String[] fieldsToCheck = new String[]{'Id','Name'};
        for(String field : fieldsToCheck) {
            if( ! fieldDescribeTokens.get(field).getDescribe().isAccessible()) {
                throw new System.NoAccessException(); return null;
            }
        }
        // LETS GO
        return [SELECT Id, Name from Account];
    }
}